baseURL = "https://maksimnazaruk.github.io/testsite/"
#baseURL = "https://example.com"
languageCode = "en-us"
title = "Max Book Reviews"
theme = "hugo_theme_robust"

[Params]
  Author = "Max Nazaruk"
